class Fashion {
  String title, size, price, image, description;
  double rating;
  int pages;

  Fashion(this.title, this.size, this.price, this.image, this.description,
      this.rating, this.pages);
}

final List<Fashion> fashions = [
  Fashion(
      'Baju Atasan Laki1',
      'Tersedia Ukuran: M, L, XL',
      'Rp 50.000',
      'assets/hemlaki1.JPG',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Laki2',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/hemlaki2.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      4.5,
      1),
  Fashion(
      'Baju Atasan Laki3',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/hemlaki3.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      5.0,
      1),
  Fashion(
      'Celana Bawahan Laki1',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/celana1.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.0,
      1),
  Fashion(
      'Celana Bawahan Laki2',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/celana2.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      4.8,
      1),
  Fashion(
      'Celana Bawahan Laki3',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/celana3.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      4.5,
      1),
  Fashion(
      'Baju Atasan Wanita1',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan1.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Wanita2',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan2.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Wanita3',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan3.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Rok Wanita1',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/rok1.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      4.8,
      1),
  Fashion(
      'Rok Wanita2',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/rok2.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      4.5,
      1),
  Fashion(
      'Rok Wanita3',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/rok3.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Wanita4',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan4.jpeg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Wanita5',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan5.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
  Fashion(
      'Baju Atasan Wanita6',
      'Tersedia Ukuran: S, M, L, XL',
      'Rp 50.000',
      'assets/tartan6.jpg',
      'KAMI MENJAMIN SEBELUM DIKIRIM BARANG DI QC (QUALITY CHECK) TERLEBIH DAHULU',
      3.5,
      1),
];
